/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PatientRouteRouteImport } from './routes/patient/route'
import { Route as EpisodeRouteRouteImport } from './routes/episode/route'
import { Route as EncounterRouteRouteImport } from './routes/encounter/route'
import { Route as EmrRouteRouteImport } from './routes/emr/route'
import { Route as AppointmentRouteRouteImport } from './routes/appointment/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PatientIndexRouteImport } from './routes/patient/index'
import { Route as AppointmentIndexRouteImport } from './routes/appointment/index'
import { Route as PatientResultRouteImport } from './routes/patient/result'
import { Route as PatientRegisterRouteImport } from './routes/patient/register'
import { Route as PatientDetailRouteImport } from './routes/patient/detail'
import { Route as EpisodeEpisodeIdRouteImport } from './routes/episode/$episodeId'
import { Route as EncounterEncounterIdRouteImport } from './routes/encounter/$encounterId'
import { Route as EmrEpisodeIdRouteImport } from './routes/emr/$episodeId'
import { Route as PatientEpisodeRouteRouteImport } from './routes/patient/episode/route'
import { Route as PatientEpisodeNewRouteImport } from './routes/patient/episode/new'

const PatientRouteRoute = PatientRouteRouteImport.update({
  id: '/patient',
  path: '/patient',
  getParentRoute: () => rootRouteImport,
} as any)
const EpisodeRouteRoute = EpisodeRouteRouteImport.update({
  id: '/episode',
  path: '/episode',
  getParentRoute: () => rootRouteImport,
} as any)
const EncounterRouteRoute = EncounterRouteRouteImport.update({
  id: '/encounter',
  path: '/encounter',
  getParentRoute: () => rootRouteImport,
} as any)
const EmrRouteRoute = EmrRouteRouteImport.update({
  id: '/emr',
  path: '/emr',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentRouteRoute = AppointmentRouteRouteImport.update({
  id: '/appointment',
  path: '/appointment',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientIndexRoute = PatientIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PatientRouteRoute,
} as any)
const AppointmentIndexRoute = AppointmentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppointmentRouteRoute,
} as any)
const PatientResultRoute = PatientResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => PatientRouteRoute,
} as any)
const PatientRegisterRoute = PatientRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => PatientRouteRoute,
} as any)
const PatientDetailRoute = PatientDetailRouteImport.update({
  id: '/detail',
  path: '/detail',
  getParentRoute: () => PatientRouteRoute,
} as any)
const EpisodeEpisodeIdRoute = EpisodeEpisodeIdRouteImport.update({
  id: '/$episodeId',
  path: '/$episodeId',
  getParentRoute: () => EpisodeRouteRoute,
} as any)
const EncounterEncounterIdRoute = EncounterEncounterIdRouteImport.update({
  id: '/$encounterId',
  path: '/$encounterId',
  getParentRoute: () => EncounterRouteRoute,
} as any)
const EmrEpisodeIdRoute = EmrEpisodeIdRouteImport.update({
  id: '/$episodeId',
  path: '/$episodeId',
  getParentRoute: () => EmrRouteRoute,
} as any)
const PatientEpisodeRouteRoute = PatientEpisodeRouteRouteImport.update({
  id: '/episode',
  path: '/episode',
  getParentRoute: () => PatientRouteRoute,
} as any)
const PatientEpisodeNewRoute = PatientEpisodeNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => PatientEpisodeRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/appointment': typeof AppointmentRouteRouteWithChildren
  '/emr': typeof EmrRouteRouteWithChildren
  '/encounter': typeof EncounterRouteRouteWithChildren
  '/episode': typeof EpisodeRouteRouteWithChildren
  '/patient': typeof PatientRouteRouteWithChildren
  '/patient/episode': typeof PatientEpisodeRouteRouteWithChildren
  '/emr/$episodeId': typeof EmrEpisodeIdRoute
  '/encounter/$encounterId': typeof EncounterEncounterIdRoute
  '/episode/$episodeId': typeof EpisodeEpisodeIdRoute
  '/patient/detail': typeof PatientDetailRoute
  '/patient/register': typeof PatientRegisterRoute
  '/patient/result': typeof PatientResultRoute
  '/appointment/': typeof AppointmentIndexRoute
  '/patient/': typeof PatientIndexRoute
  '/patient/episode/new': typeof PatientEpisodeNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/emr': typeof EmrRouteRouteWithChildren
  '/encounter': typeof EncounterRouteRouteWithChildren
  '/episode': typeof EpisodeRouteRouteWithChildren
  '/patient/episode': typeof PatientEpisodeRouteRouteWithChildren
  '/emr/$episodeId': typeof EmrEpisodeIdRoute
  '/encounter/$encounterId': typeof EncounterEncounterIdRoute
  '/episode/$episodeId': typeof EpisodeEpisodeIdRoute
  '/patient/detail': typeof PatientDetailRoute
  '/patient/register': typeof PatientRegisterRoute
  '/patient/result': typeof PatientResultRoute
  '/appointment': typeof AppointmentIndexRoute
  '/patient': typeof PatientIndexRoute
  '/patient/episode/new': typeof PatientEpisodeNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/appointment': typeof AppointmentRouteRouteWithChildren
  '/emr': typeof EmrRouteRouteWithChildren
  '/encounter': typeof EncounterRouteRouteWithChildren
  '/episode': typeof EpisodeRouteRouteWithChildren
  '/patient': typeof PatientRouteRouteWithChildren
  '/patient/episode': typeof PatientEpisodeRouteRouteWithChildren
  '/emr/$episodeId': typeof EmrEpisodeIdRoute
  '/encounter/$encounterId': typeof EncounterEncounterIdRoute
  '/episode/$episodeId': typeof EpisodeEpisodeIdRoute
  '/patient/detail': typeof PatientDetailRoute
  '/patient/register': typeof PatientRegisterRoute
  '/patient/result': typeof PatientResultRoute
  '/appointment/': typeof AppointmentIndexRoute
  '/patient/': typeof PatientIndexRoute
  '/patient/episode/new': typeof PatientEpisodeNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/appointment'
    | '/emr'
    | '/encounter'
    | '/episode'
    | '/patient'
    | '/patient/episode'
    | '/emr/$episodeId'
    | '/encounter/$encounterId'
    | '/episode/$episodeId'
    | '/patient/detail'
    | '/patient/register'
    | '/patient/result'
    | '/appointment/'
    | '/patient/'
    | '/patient/episode/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/emr'
    | '/encounter'
    | '/episode'
    | '/patient/episode'
    | '/emr/$episodeId'
    | '/encounter/$encounterId'
    | '/episode/$episodeId'
    | '/patient/detail'
    | '/patient/register'
    | '/patient/result'
    | '/appointment'
    | '/patient'
    | '/patient/episode/new'
  id:
    | '__root__'
    | '/'
    | '/appointment'
    | '/emr'
    | '/encounter'
    | '/episode'
    | '/patient'
    | '/patient/episode'
    | '/emr/$episodeId'
    | '/encounter/$encounterId'
    | '/episode/$episodeId'
    | '/patient/detail'
    | '/patient/register'
    | '/patient/result'
    | '/appointment/'
    | '/patient/'
    | '/patient/episode/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppointmentRouteRoute: typeof AppointmentRouteRouteWithChildren
  EmrRouteRoute: typeof EmrRouteRouteWithChildren
  EncounterRouteRoute: typeof EncounterRouteRouteWithChildren
  EpisodeRouteRoute: typeof EpisodeRouteRouteWithChildren
  PatientRouteRoute: typeof PatientRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/patient': {
      id: '/patient'
      path: '/patient'
      fullPath: '/patient'
      preLoaderRoute: typeof PatientRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/episode': {
      id: '/episode'
      path: '/episode'
      fullPath: '/episode'
      preLoaderRoute: typeof EpisodeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/encounter': {
      id: '/encounter'
      path: '/encounter'
      fullPath: '/encounter'
      preLoaderRoute: typeof EncounterRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emr': {
      id: '/emr'
      path: '/emr'
      fullPath: '/emr'
      preLoaderRoute: typeof EmrRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointment': {
      id: '/appointment'
      path: '/appointment'
      fullPath: '/appointment'
      preLoaderRoute: typeof AppointmentRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/': {
      id: '/patient/'
      path: '/'
      fullPath: '/patient/'
      preLoaderRoute: typeof PatientIndexRouteImport
      parentRoute: typeof PatientRouteRoute
    }
    '/appointment/': {
      id: '/appointment/'
      path: '/'
      fullPath: '/appointment/'
      preLoaderRoute: typeof AppointmentIndexRouteImport
      parentRoute: typeof AppointmentRouteRoute
    }
    '/patient/result': {
      id: '/patient/result'
      path: '/result'
      fullPath: '/patient/result'
      preLoaderRoute: typeof PatientResultRouteImport
      parentRoute: typeof PatientRouteRoute
    }
    '/patient/register': {
      id: '/patient/register'
      path: '/register'
      fullPath: '/patient/register'
      preLoaderRoute: typeof PatientRegisterRouteImport
      parentRoute: typeof PatientRouteRoute
    }
    '/patient/detail': {
      id: '/patient/detail'
      path: '/detail'
      fullPath: '/patient/detail'
      preLoaderRoute: typeof PatientDetailRouteImport
      parentRoute: typeof PatientRouteRoute
    }
    '/episode/$episodeId': {
      id: '/episode/$episodeId'
      path: '/$episodeId'
      fullPath: '/episode/$episodeId'
      preLoaderRoute: typeof EpisodeEpisodeIdRouteImport
      parentRoute: typeof EpisodeRouteRoute
    }
    '/encounter/$encounterId': {
      id: '/encounter/$encounterId'
      path: '/$encounterId'
      fullPath: '/encounter/$encounterId'
      preLoaderRoute: typeof EncounterEncounterIdRouteImport
      parentRoute: typeof EncounterRouteRoute
    }
    '/emr/$episodeId': {
      id: '/emr/$episodeId'
      path: '/$episodeId'
      fullPath: '/emr/$episodeId'
      preLoaderRoute: typeof EmrEpisodeIdRouteImport
      parentRoute: typeof EmrRouteRoute
    }
    '/patient/episode': {
      id: '/patient/episode'
      path: '/episode'
      fullPath: '/patient/episode'
      preLoaderRoute: typeof PatientEpisodeRouteRouteImport
      parentRoute: typeof PatientRouteRoute
    }
    '/patient/episode/new': {
      id: '/patient/episode/new'
      path: '/new'
      fullPath: '/patient/episode/new'
      preLoaderRoute: typeof PatientEpisodeNewRouteImport
      parentRoute: typeof PatientEpisodeRouteRoute
    }
  }
}

interface AppointmentRouteRouteChildren {
  AppointmentIndexRoute: typeof AppointmentIndexRoute
}

const AppointmentRouteRouteChildren: AppointmentRouteRouteChildren = {
  AppointmentIndexRoute: AppointmentIndexRoute,
}

const AppointmentRouteRouteWithChildren =
  AppointmentRouteRoute._addFileChildren(AppointmentRouteRouteChildren)

interface EmrRouteRouteChildren {
  EmrEpisodeIdRoute: typeof EmrEpisodeIdRoute
}

const EmrRouteRouteChildren: EmrRouteRouteChildren = {
  EmrEpisodeIdRoute: EmrEpisodeIdRoute,
}

const EmrRouteRouteWithChildren = EmrRouteRoute._addFileChildren(
  EmrRouteRouteChildren,
)

interface EncounterRouteRouteChildren {
  EncounterEncounterIdRoute: typeof EncounterEncounterIdRoute
}

const EncounterRouteRouteChildren: EncounterRouteRouteChildren = {
  EncounterEncounterIdRoute: EncounterEncounterIdRoute,
}

const EncounterRouteRouteWithChildren = EncounterRouteRoute._addFileChildren(
  EncounterRouteRouteChildren,
)

interface EpisodeRouteRouteChildren {
  EpisodeEpisodeIdRoute: typeof EpisodeEpisodeIdRoute
}

const EpisodeRouteRouteChildren: EpisodeRouteRouteChildren = {
  EpisodeEpisodeIdRoute: EpisodeEpisodeIdRoute,
}

const EpisodeRouteRouteWithChildren = EpisodeRouteRoute._addFileChildren(
  EpisodeRouteRouteChildren,
)

interface PatientEpisodeRouteRouteChildren {
  PatientEpisodeNewRoute: typeof PatientEpisodeNewRoute
}

const PatientEpisodeRouteRouteChildren: PatientEpisodeRouteRouteChildren = {
  PatientEpisodeNewRoute: PatientEpisodeNewRoute,
}

const PatientEpisodeRouteRouteWithChildren =
  PatientEpisodeRouteRoute._addFileChildren(PatientEpisodeRouteRouteChildren)

interface PatientRouteRouteChildren {
  PatientEpisodeRouteRoute: typeof PatientEpisodeRouteRouteWithChildren
  PatientDetailRoute: typeof PatientDetailRoute
  PatientRegisterRoute: typeof PatientRegisterRoute
  PatientResultRoute: typeof PatientResultRoute
  PatientIndexRoute: typeof PatientIndexRoute
}

const PatientRouteRouteChildren: PatientRouteRouteChildren = {
  PatientEpisodeRouteRoute: PatientEpisodeRouteRouteWithChildren,
  PatientDetailRoute: PatientDetailRoute,
  PatientRegisterRoute: PatientRegisterRoute,
  PatientResultRoute: PatientResultRoute,
  PatientIndexRoute: PatientIndexRoute,
}

const PatientRouteRouteWithChildren = PatientRouteRoute._addFileChildren(
  PatientRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppointmentRouteRoute: AppointmentRouteRouteWithChildren,
  EmrRouteRoute: EmrRouteRouteWithChildren,
  EncounterRouteRoute: EncounterRouteRouteWithChildren,
  EpisodeRouteRoute: EpisodeRouteRouteWithChildren,
  PatientRouteRoute: PatientRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
