/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PatientRouteRouteImport } from './routes/patient/route'
import { Route as AppointmentRouteRouteImport } from './routes/appointment/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PatientIndexRouteImport } from './routes/patient/index'
import { Route as AppointmentIndexRouteImport } from './routes/appointment/index'
import { Route as PatientResultRouteImport } from './routes/patient/result'
import { Route as PatientRegisterRouteImport } from './routes/patient/register'
import { Route as PatientDetailRouteImport } from './routes/patient/detail'

const PatientRouteRoute = PatientRouteRouteImport.update({
  id: '/patient',
  path: '/patient',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentRouteRoute = AppointmentRouteRouteImport.update({
  id: '/appointment',
  path: '/appointment',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientIndexRoute = PatientIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PatientRouteRoute,
} as any)
const AppointmentIndexRoute = AppointmentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppointmentRouteRoute,
} as any)
const PatientResultRoute = PatientResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => PatientRouteRoute,
} as any)
const PatientRegisterRoute = PatientRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => PatientRouteRoute,
} as any)
const PatientDetailRoute = PatientDetailRouteImport.update({
  id: '/detail',
  path: '/detail',
  getParentRoute: () => PatientRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/appointment': typeof AppointmentRouteRouteWithChildren
  '/patient': typeof PatientRouteRouteWithChildren
  '/patient/detail': typeof PatientDetailRoute
  '/patient/register': typeof PatientRegisterRoute
  '/patient/result': typeof PatientResultRoute
  '/appointment/': typeof AppointmentIndexRoute
  '/patient/': typeof PatientIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/patient/detail': typeof PatientDetailRoute
  '/patient/register': typeof PatientRegisterRoute
  '/patient/result': typeof PatientResultRoute
  '/appointment': typeof AppointmentIndexRoute
  '/patient': typeof PatientIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/appointment': typeof AppointmentRouteRouteWithChildren
  '/patient': typeof PatientRouteRouteWithChildren
  '/patient/detail': typeof PatientDetailRoute
  '/patient/register': typeof PatientRegisterRoute
  '/patient/result': typeof PatientResultRoute
  '/appointment/': typeof AppointmentIndexRoute
  '/patient/': typeof PatientIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/appointment'
    | '/patient'
    | '/patient/detail'
    | '/patient/register'
    | '/patient/result'
    | '/appointment/'
    | '/patient/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/patient/detail'
    | '/patient/register'
    | '/patient/result'
    | '/appointment'
    | '/patient'
  id:
    | '__root__'
    | '/'
    | '/appointment'
    | '/patient'
    | '/patient/detail'
    | '/patient/register'
    | '/patient/result'
    | '/appointment/'
    | '/patient/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppointmentRouteRoute: typeof AppointmentRouteRouteWithChildren
  PatientRouteRoute: typeof PatientRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/patient': {
      id: '/patient'
      path: '/patient'
      fullPath: '/patient'
      preLoaderRoute: typeof PatientRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointment': {
      id: '/appointment'
      path: '/appointment'
      fullPath: '/appointment'
      preLoaderRoute: typeof AppointmentRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/': {
      id: '/patient/'
      path: '/'
      fullPath: '/patient/'
      preLoaderRoute: typeof PatientIndexRouteImport
      parentRoute: typeof PatientRouteRoute
    }
    '/appointment/': {
      id: '/appointment/'
      path: '/'
      fullPath: '/appointment/'
      preLoaderRoute: typeof AppointmentIndexRouteImport
      parentRoute: typeof AppointmentRouteRoute
    }
    '/patient/result': {
      id: '/patient/result'
      path: '/result'
      fullPath: '/patient/result'
      preLoaderRoute: typeof PatientResultRouteImport
      parentRoute: typeof PatientRouteRoute
    }
    '/patient/register': {
      id: '/patient/register'
      path: '/register'
      fullPath: '/patient/register'
      preLoaderRoute: typeof PatientRegisterRouteImport
      parentRoute: typeof PatientRouteRoute
    }
    '/patient/detail': {
      id: '/patient/detail'
      path: '/detail'
      fullPath: '/patient/detail'
      preLoaderRoute: typeof PatientDetailRouteImport
      parentRoute: typeof PatientRouteRoute
    }
  }
}

interface AppointmentRouteRouteChildren {
  AppointmentIndexRoute: typeof AppointmentIndexRoute
}

const AppointmentRouteRouteChildren: AppointmentRouteRouteChildren = {
  AppointmentIndexRoute: AppointmentIndexRoute,
}

const AppointmentRouteRouteWithChildren =
  AppointmentRouteRoute._addFileChildren(AppointmentRouteRouteChildren)

interface PatientRouteRouteChildren {
  PatientDetailRoute: typeof PatientDetailRoute
  PatientRegisterRoute: typeof PatientRegisterRoute
  PatientResultRoute: typeof PatientResultRoute
  PatientIndexRoute: typeof PatientIndexRoute
}

const PatientRouteRouteChildren: PatientRouteRouteChildren = {
  PatientDetailRoute: PatientDetailRoute,
  PatientRegisterRoute: PatientRegisterRoute,
  PatientResultRoute: PatientResultRoute,
  PatientIndexRoute: PatientIndexRoute,
}

const PatientRouteRouteWithChildren = PatientRouteRoute._addFileChildren(
  PatientRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppointmentRouteRoute: AppointmentRouteRouteWithChildren,
  PatientRouteRoute: PatientRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
